# ./nginx/nginx.conf
worker_processes auto;
error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # 引入 conf.d 下的所有 .conf 文件
    include /usr/local/openresty/nginx/conf/conf.d/*.conf;
}
