server:
  port: 33331

ttcVersion: 2026.10

spring:
  application:
    name: taotao-cloud-sys
  cloud:
    nacos:
      discovery:
        server-addr: ${remote-ip}:8848
        namespace: 82f5c2ff-c0d5-478d-9987-7f082d1a55d7
        username: nacos
        password: nacos
        group: TAOTAO_CLOUD_GROUP
      config:
        enabled: true
        server-addr: ${remote-ip}:8848
        namespace: 82f5c2ff-c0d5-478d-9987-7f082d1a55d7
        username: nacos
        password: nacos
        group: TAOTAO_CLOUD_GROUP
  config:
    import:
      - optional:nacos:taotao-cloud-sys-nacos.yaml
