services:
  doris-fe-4.1.3:
    image: apache/doris:fe-4.1.3
    container_name: doris-fe-4.1.3
    hostname: doris-fe-4.1.3
    restart: no
    working_dir: /opt/apache-doris
    environment:
      FE_SERVERS: fe1:172.11.0.80:9010
      FE_ID: "1"
    entrypoint: ["/bin/bash", "-ec"]
    command:
      - |
        sed -i 's/-Xmx8192m/-Xmx1200m/g' /opt/apache-doris/fe/conf/fe.conf
        sed -i 's/-Xms8192m/-Xms1200m/g' /opt/apache-doris/fe/conf/fe.conf
        exec bash init_fe.sh
    volumes:
      - ./dockervolumes/doris/fe-meta:/opt/apache-doris/fe/doris-meta
    ports:
      - "8030:8030"
      - "9030:9030"
    networks:
      taotao-cluster-network:
        ipv4_address: 172.11.0.80
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9030' && curl -sf http://127.0.0.1:8030/api/bootstrap"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
  doris-be-4.1.3:
    image: apache/doris:be-4.1.3
    container_name: doris-be-4.1.3
    hostname: doris-be-4.1.3
    restart: no
    working_dir: /opt/apache-doris
    environment:
      FE_SERVERS: fe1:172.11.0.80:9010
      BE_ADDR: 172.11.0.81:9050
      BE_MAX_MEMORY_LIMIT: "4G"
    depends_on:
      doris-fe-4.1.3:
        condition: service_healthy
    volumes:
      - ./dockervolumes/doris/be-storage:/opt/apache-doris/be/storage
    ports:
      - "8040:8040"
    networks:
      taotao-cluster-network:
        ipv4_address: 172.11.0.81
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8040/api/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
      
  flink-jobmanager-2.3.0:
    image: apache/flink:2.3.0-scala_2.12-java21
    container_name: flink-jobmanager-2.3.0
    hostname: flink-jobmanager-2.3.0
    restart: no
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: 172.11.0.82
    networks:
      taotao-cluster-network:
        ipv4_address: 172.11.0.82
  flink-taskmanager-2.3.0:
    image: apache/flink:2.3.0-scala_2.12-java21
    container_name: flink-taskmanager-2.3.0
    hostname: flink-taskmanager-2.3.0
    restart: no
    depends_on:
      - flink-jobmanager-2.3.0
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: 172.11.0.82
        taskmanager.numberOfTaskSlots: 2
    networks:
      taotao-cluster-network:
        ipv4_address: 172.11.0.83
  flink-sql-client-2.3.0:
    image: apache/flink:2.3.0-scala_2.12-java21
    depends_on:
      - flink-jobmanager-2.3.0
    command: bin/sql-client.sh
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: 172.11.0.82
        rest.address: 172.11.0.82
    networks:
      taotao-cluster-network:
        ipv4_address: 172.11.0.84


networks:
  taotao-cluster-network:
    external: true
