brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
# broker 暴露的IP地址
brokerIP1=172.11.0.20
autoCreateTopicEnable=true
# 开启认证功能
authenticationEnabled=true
authenticationProvider=org.apache.rocketmq.auth.authentication.provider.DefaultAuthenticationProvider
initAuthenticationUser={"username":"taotaocloud","password":"taotaocloud"}
innerClientAuthenticationCredentials={"accessKey":"taotaocloud","secretKey":"taotaocloud"}
authenticationMetadataProvider=org.apache.rocketmq.auth.authentication.provider.LocalAuthenticationMetadataProvider
# 开启授权功能
authorizationEnabled=true
authorizationProvider=org.apache.rocketmq.auth.authorization.provider.DefaultAuthorizationProvider
authorizationMetadataProvider=org.apache.rocketmq.auth.authorization.provider.LocalAuthorizationMetadataProvider
# 兼容 ACL 1.0 的 plain_acl.yml 文件
migrateAuthFromV1Enabled=true
